config/routes.rb
Rails.application.routes.draw do
  resources :signups
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/signup.rb
class Signup < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :set_signup, only: %i[ show edit update destroy ]

  # GET /signups or /signups.json
  def index
    @signups = Signup.all
  end

  # GET /signups/1 or /signups/1.json
  def show
  end

  # GET /signups/new
  def new
    @signup = Signup.new
  end

  # GET /signups/1/edit
  def edit
  end

  # POST /signups or /signups.json
  def create
    @signup = Signup.new(signup_params)

    respond_to do |format|
      if @signup.save
        format.html { redirect_to signup_url(@signup), notice: "Signup was successfully created." }
        format.json { render :show, status: :created, location: @signup }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signups/1 or /signups/1.json
  def update
    respond_to do |format|
      if @signup.update(signup_params)
        format.html { redirect_to signup_url(@signup), notice: "Signup was successfully updated." }
        format.json { render :show, status: :ok, location: @signup }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signups/1 or /signups/1.json
  def destroy
    @signup.destroy

    respond_to do |format|
      format.html { redirect_to signups_url, notice: "Signup was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signup
      @signup = Signup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def signup_params
      params.require(:signup).permit(:playernames, :dateofbirth, :caregivernames, :phone, :relationship, :clinic, :team)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImsShamas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/signups/_form.html.erb
<%= form_with(model: signup) do |form| %>
  <% if signup.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(signup.errors.count, "error") %> prohibited this signup from being saved:</h2>

      <ul>
        <% signup.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :playernames, style: "display: block" %>
    <%= form.text_field :playernames %>
  </div>

  <div>
    <%= form.label :dateofbirth, style: "display: block" %>
    <%= form.date_field :dateofbirth %>
  </div>

  <div>
    <%= form.label :caregivernames, style: "display: block" %>
    <%= form.text_field :caregivernames %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :relationship, style: "display: block" %>
    <%= form.text_field :relationship %>
  </div>

  <div>
    <%= form.label :clinic, style: "display: block" %>
    <%= form.text_field :clinic %>
  </div>

  <div>
    <%= form.label :team, style: "display: block" %>
    <%= form.text_field :team %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/signups/_signup.html.erb
<div id="<%= dom_id signup %>">
  <p>
    <strong>Player Names:</strong>
    <%= signup.playernames %>
  </p>

  <p>
    <strong>Date of Birth:</strong>
    <%= signup.dateofbirth %>
  </p>

  <p>
    <strong>Caregiver Names:</strong>
    <%= signup.caregivernames %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= signup.phone %>
  </p>

  <p>
    <strong>Relationship:</strong>
    <%= signup.relationship %>
  </p>

  <p>
    <strong>Clinic:</strong>
    <%= signup.clinic %>
  </p>

  <p>
    <strong>Team:</strong>
    <%= signup.team %>
  </p>

</div>

app/views/signups/edit.html.erb
<h1>Editing signup</h1>

<%= render "form", signup: @signup %>

<br>

<div>
  <%= link_to "Show this signup", @signup %> |
  <%= link_to "Back to signups", signups_path %>
</div>

app/views/signups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sign Up Players</h1>

<div id="signups">
  <% @signups.each do |signup| %>
    <%= render signup %>
    <p>
      <%= link_to "Show this signup", signup %>
    </p>
  <% end %>
</div>

<%= link_to "New signup", new_signup_path %>

app/views/signups/new.html.erb
<h1>New signup</h1>

<%= render "form", signup: @signup %>

<br>

<div>
  <%= link_to "Back to signups", signups_path %>
</div>

app/views/signups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @signup %>

<div>
  <%= link_to "Edit this signup", edit_signup_path(@signup) %> |
  <%= link_to "Back to signups", signups_path %>

  <%= button_to "Destroy this signup", @signup, method: :delete %>
</div>